name: SSH Actions Demo

on:
    push:
      branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      
      - name: Run a one-line script
        run: echo Hello, world!

      - name: rsync deployments
        run: |
          set -eu
          mkdir "$HOME/.ssh"
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > "$HOME/.ssh/key"
          chmod 600 "$HOME/.ssh/key"
          rsync -e "ssh -p 65002 -i $HOME/.ssh/key" --archive --compress --delete ./src u442453973@92.113.18.216:/home/u442453973/domains/crm.cv.ua/public_html/r-dev/www/
